export const insertPO = [
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(1,'A catégoriser' ,'#e6b3ff')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(2,'Aides, indémnisation', '#ffcce6')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(3,'Alimentation, concentrés','#f7e6ff')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(4,'Banque, Epargne', '#ff99cc')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(5,'Banque, Intérét','#ff99cc')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(6,'Batiment, Aménagement batiment', '#ccd9ff')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(7,'Fertilisation, engrais minéral', '#ccffcc')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(8,'Foncier, achat de terrain','#ccffcc')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(9,'Fonctionnement général', '#f2d9d9')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(10,'Fonctionnement général, assurance', '#ccd9ff')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(11,'Fonctionnement général, eau', '#ccd9ff')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(12,'Fonctionnement général, électricité', '#ffcce6')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(13,'Fonctionnement général, fournitures', '#f2d9d9')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(14,'Fonctionnement général, Frais postaux', '#ccd9ff')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(15,'Fonctionnement général, internet', '#ccffcc')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(16,'Fonctionnement général, Téléphone', '#ff99cc')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(17,'Main d oeuvre, aide', '#d9f2d9')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(18,'Main d oeuvre, MSA', '#d9f2d9')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(19,'Main d oeuvre, salaire', '#ff99cc')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(20,'Matériel, achat', '#ddffcc')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(21,'Matériel, carburant', '#d9f2d9' )",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(22,'Matériel, entretien ', '#f2d9d9')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(23,'Matériel, Remboursement emprunt', '#ffcce6')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(24,'Produit lait','#d9f2d9')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(25,'Reproduction, IA', '#f2d9d9')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(26,'Sanitaire, indémnisation' ,'#ddffcc')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(27,'Subvention, aides PAC', '#f2d9d9')",
"Insert into Poste (idPoste, libPoste, couleurPoste) VALUES(28,'Vente, taurillon', '#ddffcc')"]; 
